serial:
  port: auto
  baudrate: 115200
  timeout: 1.0
sampling_rate_hz: 200
emg_sensors: 2
active_profile: work_mode
gesture_labels:
- rest
- left_single
- right_single
- left_double
- right_double
- left_hold
- right_hold
- both_flex
- left_then_right
- right_then_left
- left_hard
- right_hard
modes:
  work_mode: 1
  game_mode: 2
  creative_mode: 3
  default_mode: 0
default_gesture_keys:
  rest: null
  left_single: ctrl+c
  right_single: ctrl+v
  left_double: ctrl+z
  right_double: ctrl+y
  left_hold: ctrl+s
  right_hold: ctrl+a
  both_flex: ctrl+shift+z
  left_then_right: ctrl+x
  right_then_left: ctrl+f
  left_hard: ctrl+shift+c
  right_hard: ctrl+shift+v
current_keys:
  rest: null
  left_single: tab
  right_single: enter
  left_double: escape
  right_double: space
  left_hold: ctrl
  right_hold: alt
  both_flex: shift
  left_then_right: f1
  right_then_left: f2
  left_hard: f3
  right_hard: f4
mode_key_overrides:
  work_mode:
    left_single: ctrl+c
    right_single: ctrl+v
    left_double: ctrl+z
    right_double: ctrl+y
    left_hold: ctrl+s
    right_hold: ctrl+a
    both_flex: ctrl+shift+z
    left_then_right: ctrl+x
    right_then_left: ctrl+f
    left_hard: ctrl+shift+c
    right_hard: ctrl+shift+v
  game_mode:
    left_single: w
    right_single: s
    left_double: a
    right_double: d
    left_hold: shift
    right_hold: space
    both_flex: ctrl
    left_then_right: e
    right_then_left: r
    left_hard: '1'
    right_hard: '2'
  creative_mode:
    left_single: ctrl+z
    right_single: ctrl+y
    left_double: ctrl+c
    right_double: ctrl+v
    left_hold: ctrl+s
    right_hold: ctrl+a
    both_flex: ctrl+shift+z
    left_then_right: ctrl+x
    right_then_left: ctrl+f
    left_hard: ctrl+shift+c
    right_hard: ctrl+shift+v
  default_mode:
    left_single: tab
    right_single: enter
    left_double: escape
    right_double: space
    left_hold: ctrl
    right_hold: alt
    both_flex: shift
    left_then_right: f1
    right_then_left: f2
    left_hard: f3
    right_hard: f4
app_mode_mapping:
  Visual Studio Code: work_mode
  Code: work_mode
  cursor: work_mode
  Xcode: work_mode
  Safari: default_mode
  Google Chrome: default_mode
  Arc: default_mode
  Steam: game_mode
  Unity: game_mode
  Unreal: game_mode
  Blender: creative_mode
  Photoshop: creative_mode
  Illustrator: creative_mode
  Figma: creative_mode
output_dir: data/raw
