serial:
  port: auto
  baudrate: 115200
  timeout: 1.0

sampling_rate_hz: 200
emg_sensors: 2 

gesture_labels: ["rest", "flex", "hold", "click", "double_click", "wrist_up", "wrist_down"]

# map modes for adk
modes:
  work_mode: 1
  game_mode: 2
  creative_mode: 3
  default_mode: 0

# settings
output_dir: "data/raw"
